### ISSUE TITLE
关于问题#01

### ISSUE THREAD

**Issue by virgil698** [GaleMC/Gale#2]
![7a08f113a8506ee30a82751270eabaac](https://user-images.githubusercontent.com/83110631/213678200-cadfe97a-d9b7-40dc-9391-1d3c42226a73.png)
全部插件加载完后输入stopstop就卡在这里了
![8347612eacb1ef5bfddb2d89be6d4334](https://user-images.githubusercontent.com/83110631/213678290-2df8bd3f-e0ad-4baf-b8da-f6a9f0d1ab46.png)
通过后台面板查看发现服务器shu ru输入stop后还处在于待机状态

**Comment by ghost** [comment]
emmm,这服务端还没加载完吧（）

**Comment by ghost** [comment]
> emmm,这服务端还没加载完吧（）

emmm，你在reload？

**Comment by xiaozhangup** [comment]
尽管开发者确实能看懂中文（不是中文母语者），但还是请使用英文描述。

**Comment by nostalfinals** [comment]
开发者不是中国人。请使用英文进行描述。

**Comment by virgil698** [comment]
ok

**Comment by MartijnMuijsers** [comment]
没事，谢谢你提问题~
（用英语更容易懂，但你写的我看得懂）

我检查呢，谢谢。

**Comment by MartijnMuijsers** [comment]
(In the meantime, this issue is no longer present in 1.20~)

Thank you again for reporting!
