### ISSUE TITLE
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached

### ISSUE THREAD

**Issue by ifloppy** [GaleMC/Gale#4]
![image](https://user-images.githubusercontent.com/68799904/219668491-85b5a1af-bc8b-46a7-abc7-eaf347634c29.png)
Dear GaleMC,

I am writing to report an issue that I am encountering with the latest build of your server software (Ignore null or empty polled chunk cache tasks #22), which I am using to run a Minecraft server. Unfortunately, after starting the server with this new build, the server software crashed unexpectedly.

I would like to note that I have plenty of available CPU, memory, and disk resources on my server, and I did not experience this issue with the previous build (#20). I am providing a copy of the crash report below for your reference.

I would appreciate any assistance you can provide in resolving this issue, and any guidance you can offer to prevent this issue from occurring in the future.

Thank you for your attention to this matter.

Best regards,

ifloppy

[Crash report:
[crash-2023-02-17_08.04.32-server.txt](https://github.com/GaleMC/Gale/files/10767209/crash-2023-02-17_08.04.32-server.txt)
[crash-2023-02-17_08.13.25-server.txt](https://github.com/GaleMC/Gale/files/10767211/crash-2023-02-17_08.13.25-server.txt)
[crash-2023-02-17_08.21.44-server.txt](https://github.com/GaleMC/Gale/files/10767213/crash-2023-02-17_08.21.44-server.txt)

_The letter part was generated with ChatGPT, I told it what problem I had and asked him to report the problem in the most polite way_ XD

**Comment by ifloppy** [comment]
Oddly I downloaded it to my windows computer and didn't have this problem

**Comment by ifloppy** [comment]
I probably know how the problem arises, so I adjusted the configuration file of paper and the number of CPUs allocated by ptero, and the problem has been solved

**Comment by ifloppy** [comment]
This problem came up again soon and I wonder if there is a solution

**Comment by MartijnMuijsers** [comment]
Thank you for reporting! :)

Could you try the newest build #23: https://github.com/GaleMC/Gale/actions/runs/4205635075
and see if it is fixed?

**Comment by ifloppy** [comment]
Thanks for your reply and edits.
Problem solved, thanks a lot!
