### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by NovaPixell** [GaleMC/Gale#8]
Here the Crash Report on Latest Build 1.20.1: https://mclo.gs/OjDzjHV

**Comment by MartijnMuijsers** [comment]
Thanks for the report!

For whoever sees this in the future: this is an issue in vanilla Minecraft, not Gale (it has been reported many times at every level now, from the Mojang issue tracker to Spigot and Paper). I closed this issue, but the same issue is, at the time of writing, still open for reference while I attempt to fix it in Gale: https://github.com/GaleMC/Gale/issues/6.
